### ISSUE TITLE
Default implementations for default, debug not available

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/kvm-bindings#19]
We are using FamWrapper for `kvm_cpuid2`, `kvm_msrs`, and `kvm_msr_list`. These structures have `#[derive(Default, Debug)]` macros which are pretty useful. We should make sure that their wrappers also have the derives as it makes the code nicer and easier to debug.

**Comment by lauralt** [comment]
Directly deriving `Default` or `Debug` for these alias types is not allowed since `FamStructWrapper` doesn't derive them either.

Implementing these traits is not allowed either because only traits defined in the current crate (`kvm-bindings`) can be implemented for types that are not defined in that crate (in this case `FamStructWrapper`, which is defined in `vmm-sys-util`). To avoid defining and implementing some custom traits as a replacement for `Default`, `Debug` (which would be a really weird solution), instead of alias types we could use [newtypes](https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#using-the-newtype-pattern-to-implement-external-traits-on-external-types).

`pub type Msrs = FamStructWrapper<kvm_msrs>;` -> `pub struct Msrs(FamStructWrapper<kvm_msrs>)`;

With this change, we can implement Debug and Default, for example:

```rust
impl Default for MsrList {
    fn default() -> Self {
        MsrList { 0: FamStructWrapper::new(0)}
    }
}

impl Debug for MsrList {
    fn fmt(&self, f: &mut Formatter) -> fmt::Result {
        write!(f, "MsrList {{ kvm_msr_list: {:?} }}", self.0.as_slice())
    }
}
```

The problem with this approach is that, even if we implement `Deref` and `DerefMut` for these types, the change remains a breaking change for the interface (we should, among others, redefine some methods from `FamStructWrapper` for the new type, e.g.: `new()`, `from_entries()`).
So from what it looks like, there is no nice solution to fix this without having breaking changes.
