### ISSUE TITLE
Add CODEOWNERS file

### ISSUE THREAD

**Issue by rbradford** [rust-vmm/kvm-bindings#2]
Please add a CODEOWNERS file with the details of the maintainers. Please use the following format as outlined in: https://help.github.com/en/articles/about-code-owners

Most projects can simply follow the wildcard syntax. e.g.

`* @owner1 @owner2`

Not only does this provide a way to see who is responsible or this repository they will also automatically be notified of incoming PR reviews.

**Comment by aghecenco** [comment]
File added

**Comment by lauralt** [comment]
We do have a file, but not codeowners, so not sure if we should close the issue.

**Comment by andreeaflorescu** [comment]
We can handle that in a separate issue because this one was about adding the file. The problem with the codeowners is that we no longer use pull requests assigner. We can use the gatekeepers team instead. I think that could make more sense until we have any other explicit owners for the crates. WDYT @lauralt @aghecenco?
